#!/usr/bin/lua

local posix = require("posix")

local PATH = arg[1] or ""

local ICONS = {}
for icon in (arg[2] or ""):gmatch("[^,]+") do
	ICONS[#ICONS + 1] = icon .. " "
end

local COLORS = {}
for color in (arg[3] or "white,white,white,white,white,white,white,white,yellow,red"):gmatch("[^,]+") do
	COLORS[#COLORS + 1] = color
end

for i, v in ipairs(COLORS) do
	print(i, v)
end

---@return any, string?
local function load_statscore_safely(path)
	local env = {}

	local get_statscore, err
	if setfenv then
		get_statscore, err = loadfile(path)
		get_statscore = get_statscore and setfenv(get_statscore, env)
	else
		get_statscore, err = loadfile(path, "t", env)
	end
	if not get_statscore then
		return nil, "Loading file failed: " .. err
	end

	local ok, res = pcall(get_statscore)
	if not ok then
		return nil, "Executing file failed: " .. tostring(res)
	end

	return res
end

while true do
	local statscore, err = load_statscore_safely("/dev/shm/statscore.lua")
	if not statscore then
		error(err)
	end

	for part in PATH:gmatch("[.]?([^.]+)") do
		statscore = statscore or {}
		statscore = statscore[tonumber(part)] or statscore[part]
	end
	if type(statscore) == "table" then
		local value, risk = statscore.value, statscore.risk

		local statscore_str = string.format(
			"<span color='%s'>%s%s</span>",
			COLORS[math.min(math.ceil((risk + 0.001) * #COLORS), #COLORS)] or "white",
			ICONS[math.min(math.ceil((risk + 0.001) * #ICONS), #ICONS)] or "",
			value
		)
		io.write(statscore_str, "\n")
		io.flush()
	end

	posix.sleep(1)
end
